#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bantin
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TinTuc")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBanTin(BanTin instance);
    partial void UpdateBanTin(BanTin instance);
    partial void DeleteBanTin(BanTin instance);
    #endregion
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BanTin> BanTins
		{
			get
			{
				return this.GetTable<BanTin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BanTin")]
	public partial class BanTin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBanTin;
		
		private string _TieuDe;
		
		private string _NDTomTat;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _NgayDangTin;
		
		private string _HinhAnh;
		
		private string _ChuThichHinh;
		
		private string _MaLinhVuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBanTinChanging(string value);
    partial void OnMaBanTinChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnNDTomTatChanging(string value);
    partial void OnNDTomTatChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayDangTinChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangTinChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnChuThichHinhChanging(string value);
    partial void OnChuThichHinhChanged();
    partial void OnMaLinhVucChanging(string value);
    partial void OnMaLinhVucChanged();
    #endregion
		
		public BanTin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBanTin", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBanTin
		{
			get
			{
				return this._MaBanTin;
			}
			set
			{
				if ((this._MaBanTin != value))
				{
					this.OnMaBanTinChanging(value);
					this.SendPropertyChanging();
					this._MaBanTin = value;
					this.SendPropertyChanged("MaBanTin");
					this.OnMaBanTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(255)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NDTomTat", DbType="NVarChar(500)")]
		public string NDTomTat
		{
			get
			{
				return this._NDTomTat;
			}
			set
			{
				if ((this._NDTomTat != value))
				{
					this.OnNDTomTatChanging(value);
					this.SendPropertyChanging();
					this._NDTomTat = value;
					this.SendPropertyChanged("NDTomTat");
					this.OnNDTomTatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangTin", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDangTin
		{
			get
			{
				return this._NgayDangTin;
			}
			set
			{
				if ((this._NgayDangTin != value))
				{
					this.OnNgayDangTinChanging(value);
					this.SendPropertyChanging();
					this._NgayDangTin = value;
					this.SendPropertyChanged("NgayDangTin");
					this.OnNgayDangTinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuThichHinh", DbType="NVarChar(100)")]
		public string ChuThichHinh
		{
			get
			{
				return this._ChuThichHinh;
			}
			set
			{
				if ((this._ChuThichHinh != value))
				{
					this.OnChuThichHinhChanging(value);
					this.SendPropertyChanging();
					this._ChuThichHinh = value;
					this.SendPropertyChanged("ChuThichHinh");
					this.OnChuThichHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLinhVuc", DbType="Char(10)")]
		public string MaLinhVuc
		{
			get
			{
				return this._MaLinhVuc;
			}
			set
			{
				if ((this._MaLinhVuc != value))
				{
					this.OnMaLinhVucChanging(value);
					this.SendPropertyChanging();
					this._MaLinhVuc = value;
					this.SendPropertyChanged("MaLinhVuc");
					this.OnMaLinhVucChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
